<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="F_DegToRad" Id="{5200f035-ac36-40d0-a8b8-8b3584a964b4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_DegToRad : LREAL
VAR_INPUT
	fInputDeg 	: LREAL;
END_VAR
VAR
	fPi 		:LREAL := 3.14159265359;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_DegToRad := fInputDeg*(fPi/180);]]></ST>
    </Implementation>
    <LineIds Name="F_DegToRad">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>