<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="P_WinchControl" Id="{9db37c6e-a65f-4d33-b11a-5f984ef248b2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_WinchControl
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="P_WinchControl">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>